<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../WorkTracker.Shared/WorkTracker.Shared.csproj" />
    <ProjectReference Include="../WorkTracker.Users.Contracts/WorkTracker.Users.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WorkTracker.Users.Tests" />
  </ItemGroup>
</Project>
